# Generated by Django 4.0.5 on 2022-06-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='Created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='Published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
    ]
